module.exports = [
  {name: 'Accused/Alleged', id: 'Accused/Alleged'},
  {name: 'Armed forces/Military', id: 'Armed forces/Military'},
  {name: 'Asylum Seekers/Asylees', id: 'Asylum Seekers/Asylees'},
  {name: 'Businesses/Corporations', id: 'Businesses/Corporations'},
  {name: 'Children', id: 'Children'},
  {name: 'Children/Youth', id: 'Children/Youth'},
  {name: 'Civilians', id: 'Civilians'},
  {name: 'Community', id: 'Community'},
  {name: 'Courts/Judicial authorities', id: 'Courts/Judicial authorities'},
  {name: 'Criminals', id: 'Criminals'},
  {name: 'Detained Persons/Imprisoned Persons', id: 'Detained Persons/Imprisoned Persons'},
  {name: 'Displaced Persons', id: 'Displaced Persons'},
  {name: 'Economic Categories', id: 'Economic Categories'},
  {name: 'Economic unions', id: 'Economic unions'},
  {name: 'Educational Institutions', id: 'Educational Institutions'},
  {name: 'Elderly', id: 'Elderly'},
  {name: 'Employers', id: 'Employers'},
  {name: 'Ethnic/Racial', id: 'Ethnic/Racial'},
  {name: 'Family', id: 'Family'},
  {name: 'Fathers', id: 'Fathers'},
  {name: 'Government/The State', id: 'Government/The State'},
  {name: 'Immigrants', id: 'Immigrants'},
  {name: 'Indigenous/Native', id: 'Indigenous/Native'},
  {name: 'International Entities', id: 'International Entities'},
  {name: 'International Organizations', id: 'International Organizations'},
  {name: 'International Tribunals/Courts', id: 'International Tribunals/Courts'},
  {name: 'LGBTI', id: 'LGBTI'},
  {name: 'Migrants', id: 'Migrants'},
  {name: 'Missing Persons/Disappeared Persons', id: 'Missing Persons/Disappeared Persons'},
  {name: 'Mothers', id: 'Mothers'},
  {name: 'Multinational corporations', id: 'Multinational corporations'},
  {name: 'NGOs', id: 'NGOs'},
  {name: 'Non-human animals', id: 'Non-human animals'},
  {name: 'Offender/Convicted', id: 'Offender/Convicted'},
  {name: 'Parents', id: 'Parents'},
  {name: 'People', id: 'People'},
  {name: 'People on the move/Itinerant', id: 'People on the move/Itinerant'},
  {name: 'Persons with Disabilities', id: 'Persons with Disabilities'},
  {name: 'Police', id: 'Police'},
  {name: 'Political alliances', id: 'Political alliances'},
  {name: 'Political Categories',id: 'Political Categories'},
  {name: 'Political leaders/Public officials', id: 'Political leaders/Public officials'},
  {name: 'Pregnant Women', id: 'Pregnant Women'},
  {name: 'Prisoners of War', id: 'Prisoners of War'},
  {name: 'Refugees', id: 'Refugees'},
  {name: 'Religious', id: 'Religious'},
  {name: 'Religious institutions/Faith-based organizations', id: 'Religious institutions/Faith-based organizations'},
  {name: 'Sick/Wounded', id: 'Sick/Wounded'},
  {name: 'Society', id: 'Society'},
  {name: 'Stateless Persons', id: 'Stateless Persons'},
  {name: 'The Catholic Church', id: 'The Catholic Church'},
  {name: 'Unborn/Fetus', id: 'Unborn/Fetus'},
  {name: 'Unions', id: 'Unions'},
  {name: 'Victims', id: 'Victims'},
  {name: 'Vulnerable/Poor', id: 'Vulnerable/Poor'},
  {name: 'Women',id: 'Women'},
  {name: 'Workers/Employees', id: 'Workers/Employees'}
]
