module.exports = [
    {name: 'People', id: 'people'},
    {name: 'Criminals', id: 'criminals'},
    {name: 'Accused/Alleged', id: 'accused alleged'},
    {name: 'Offender/Convicted', id: 'offender convicted'},
    {name: 'Economic Categories', id: 'economic categories'},
    {name: 'Workers/Employees', id: 'workers employees'},
    {name: 'Employers', id: 'employers'},
    {name: 'Family', id: 'family'},
    {name: 'Parents', id: 'parents'},
    {name: 'Children', id: 'children'},
    {name: 'Mothers', id: 'mothers'},
    {name: 'Fathers', id: 'fathers'},
    {name: 'Special Categories', id: 'special categories'},
    {name: 'Children/Youth', id: 'children youth'},
    {name: 'Elderly', id: 'elderly'},
    {name: 'Indigenous/Native', id: 'indigenous native'},
    {name: 'LGBTI', id: 'LGBTI'},
    {name: 'Persons with Disabilities', id: 'persons with disabilities'},
    {name: 'Religious', id: 'religious'},
    {name: 'Ethnic/Racial', id: 'ethnic racial'},
    {name: 'Sick/Wounded', id: 'sick wounded'},
    {name: 'Unborn/Fetus', id: 'unborn fetus'},
    {name: 'Political Categories',id: 'political categories'},
    {name: 'Detained Persons/Imprisoned Persons', id: 'detained imprisoned persons'},
    {name: 'Missing Persons/Disappeared Persons', id: 'missing disappeared persons'},
    {name: 'People on the move/Itinerant', id: 'people on the move itinerant'},
    {name: 'Asylum Seekers/Asylees', id: 'asylum seekers/asylees'},
    {name: 'Immigrants', id: 'immigrants'},
    {name: 'Migrants', id: 'migrants'},
    {name: 'Refugees', id: 'refugees'},
    {name: 'Stateless Persons', id: 'stateless persons'},
    {name: 'Displaced Persons', id: 'displaced persons'},
    {name: 'Political leaders/Public officials', id: 'political leaders public officials'},
    {name: 'Courts/Judicial authorities', id: 'courts judicial authorities'},
    {name: 'Police', id: 'police'},
    {name: 'Armed forces/Military', id: 'armed forces military'},
    {name: 'Civilians', id: 'civilians'},
    {name: 'Prisoners of War', id: 'prisoners of war'},
    {name: 'Victims', id: 'Victims'},
    {name: 'Vulnerable/Poor', id: 'vulnerable poor'},
    {name: 'Women',id: 'women'},
    {name: 'Pregnant Women', id: 'pregnant women'},
    {name: 'International Entities', id: 'international entities'},
    {name: 'International Organizations', id: 'international organizations'},
    {name: 'International Tribunals/Courts', id: 'international tribunals courts'},
    {name: 'Political alliances', id: 'political alliances'},
    {name: 'Economic unions', id: 'economic unions'},
    {name: 'Multinational corporations', id: 'multinational corporations'},
    {name: 'Society', id: 'society'},
    {name: 'Religious institutions/Faith-based organizations', id: 'religious institutions/faith-based organizations'},
    {name: 'The Catholic Church', id: 'catholic church'},
    {name: 'NGOs', id: 'NGOs'},
    {name: 'Educational Institutions', id: 'educational institutions'},
    {name: 'Community', id: 'community'},
    {name: 'Unions', id: 'unions'},
    {name: 'Businesses/Corporations', id: 'businesses corporations'},
    {name: 'Government/The State', id: 'government state'},
    {name: 'Non-human animals', id: 'non-human animals'}
  ]
